package models

import "time"

// Device represents a registered device.
type Device struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Token     string    `json:"token"`
	Type      string    `json:"type"` // "desktop", "mobile", or "pc_receiver"
	CreatedAt time.Time `json:"created_at"`
}

// PairingCode represents a short-lived code generated by a desktop device.
type PairingCode struct {
	Code        string    `json:"code"`
	DesktopID   string    `json:"desktop_id"`
	DesktopName string    `json:"desktop_name,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
	GeneratedAt time.Time `json:"generated_at"`
}

// DevicePairing represents a bound desktop/mobile relationship.
type DevicePairing struct {
	DesktopID   string    `json:"desktop_id"`
	DesktopName string    `json:"desktop_name"`
	MobileID    string    `json:"mobile_id"`
	MobileName  string    `json:"mobile_name"`
	CreatedAt   time.Time `json:"created_at"`
}

// Session represents a terminal session
type Session struct {
	ID        string    `json:"id"`
	DeviceID  string    `json:"device_id"`
	Title     string    `json:"title"`
	Layout    string    `json:"layout,omitempty"`
	Status    string    `json:"status"` // "active", "closed"
	Cols      int       `json:"cols"`
	Rows      int       `json:"rows"`
	CreatedAt time.Time `json:"created_at"`
}

// OnlineStatus tracks which devices are currently connected
type OnlineStatus struct {
	DeviceID    string    `json:"device_id"`
	ConnectedAt time.Time `json:"connected_at"`
	LastSeen    time.Time `json:"last_seen"`
}

// ─── Protocol v3: typed, validated, routable ──────────────────────────────

// MsgType enumerates all valid WebSocket message types.
type MsgType string

const (
	// Auth lifecycle
	MsgAuth         MsgType = "auth"
	MsgAuthResponse MsgType = "auth_response"

	// Heartbeat, peer state, errors
	MsgHeartbeat   MsgType = "heartbeat"
	MsgDevicePeers MsgType = "device.peer_state"
	MsgError       MsgType = "error"

	// Protocol v3 control and stream messages.
	MsgPeerReplaced          MsgType = "peer.replaced"
	MsgWorkspaceList         MsgType = "workspace.list"
	MsgWorkspaceListRes      MsgType = "workspace.list_res"
	MsgWorkspaceSubscribe    MsgType = "workspace.subscribe"
	MsgWorkspaceUnsubscribe  MsgType = "workspace.unsubscribe"
	MsgLayoutSnapshot        MsgType = "layout.snapshot"
	MsgLayoutPatch           MsgType = "layout.patch"
	MsgLayoutActionRequest   MsgType = "layout.action_request"
	MsgLayoutActionResult    MsgType = "layout.action_result"
	MsgScreenSubscribe       MsgType = "screen.subscribe"
	MsgScreenUnsubscribe     MsgType = "screen.unsubscribe"
	MsgScreenSnapshot        MsgType = "screen.snapshot"
	MsgScreenDelta           MsgType = "screen.delta"
	MsgScreenAck             MsgType = "screen.ack"
	MsgScreenResyncRequest   MsgType = "screen.resync_request"
	MsgScreenHistoryRequest  MsgType = "screen.history_request"
	MsgScreenHistoryResponse MsgType = "screen.history_response"
	MsgScreenClear           MsgType = "screen.clear"
	MsgInputSend             MsgType = "input.send"
	MsgInputAck              MsgType = "input.ack"
	MsgInputReject           MsgType = "input.reject"
)

// Message is the unified envelope for all WebSocket traffic.
type Message struct {
	Type        string                 `json:"type"`
	V           int                    `json:"v,omitempty"`
	ID          string                 `json:"id,omitempty"`
	WorkspaceID string                 `json:"workspace_id,omitempty"`
	PaneID      string                 `json:"pane_id,omitempty"`
	SessionID   string                 `json:"session_id,omitempty"`
	Timestamp   int64                  `json:"timestamp"`
	Payload     map[string]interface{} `json:"payload,omitempty"`
}

// AuthPayload is the payload for auth messages.
type AuthPayload struct {
	Token                string `json:"token"`
	DeviceType           string `json:"device_type,omitempty"`
	ClientInstanceID     string `json:"client_instance_id,omitempty"`
	ConnectionGeneration int64  `json:"connection_generation,omitempty"`
	SupportedProtocols   []int  `json:"supported_protocols,omitempty"`
}

// AuthResponsePayload is the payload for auth_response messages.
type AuthResponsePayload struct {
	Success          bool   `json:"success"`
	DeviceID         string `json:"device_id"`
	DeviceType       string `json:"device_type"`
	SelectedProtocol int    `json:"selected_protocol,omitempty"`
	ConnectionID     string `json:"connection_id,omitempty"`
	Message          string `json:"message,omitempty"`
}

// PeerDeviceSnapshot is the UI-facing summary of an online paired device.
type PeerDeviceSnapshot struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Type   string `json:"type"`
	Online bool   `json:"online"`
}

// ErrorPayload is the payload for error messages.
type ErrorPayload struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// AuthRequest represents a REST login request.
type AuthRequest struct {
	Token string `json:"token"`
}

// AuthResponse represents a REST login response.
type AuthResponse struct {
	Success  bool   `json:"success"`
	DeviceID string `json:"device_id,omitempty"`
	Message  string `json:"message,omitempty"`
}
