package models

import "time"

// Device represents a registered device (desktop or mobile)
type Device struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Token     string    `json:"token"`
	Type      string    `json:"type"` // "desktop" or "mobile"
	CreatedAt time.Time `json:"created_at"`
}

// PairingCode represents a short-lived code generated by a desktop device.
type PairingCode struct {
	Code        string    `json:"code"`
	DesktopID   string    `json:"desktop_id"`
	DesktopName string    `json:"desktop_name,omitempty"`
	ExpiresAt   time.Time `json:"expires_at"`
	GeneratedAt time.Time `json:"generated_at"`
}

// DevicePairing represents a bound desktop/mobile relationship.
type DevicePairing struct {
	DesktopID   string    `json:"desktop_id"`
	DesktopName string    `json:"desktop_name"`
	MobileID    string    `json:"mobile_id"`
	MobileName  string    `json:"mobile_name"`
	CreatedAt   time.Time `json:"created_at"`
}

// Session represents a terminal session
type Session struct {
	ID        string    `json:"id"`
	DeviceID  string    `json:"device_id"`
	Title     string    `json:"title"`
	Layout    string    `json:"layout,omitempty"`
	Status    string    `json:"status"` // "active", "closed"
	Cols      int       `json:"cols"`
	Rows      int       `json:"rows"`
	CreatedAt time.Time `json:"created_at"`
}

// OnlineStatus tracks which devices are currently connected
type OnlineStatus struct {
	DeviceID    string    `json:"device_id"`
	ConnectedAt time.Time `json:"connected_at"`
	LastSeen    time.Time `json:"last_seen"`
}

// ─── Protocol v2: typed, validated, routable ──────────────────────────────

// MsgType enumerates all valid WebSocket message types.
type MsgType string

const (
	// Auth lifecycle
	MsgAuth         MsgType = "auth"
	MsgAuthResponse MsgType = "auth_response"

	// Session lifecycle (owner-only)
	MsgSessionCreate        MsgType = "session.create"
	MsgSessionCreateRequest MsgType = "session.create_request"
	MsgSessionClose         MsgType = "session.close"
	MsgSessionCloseRequest  MsgType = "session.close_request"
	MsgSessionUpdate        MsgType = "session.update"
	MsgSessionListReq       MsgType = "session.list"
	MsgSessionListRes       MsgType = "session.list_res"

	// Terminal I/O (owner writes output; viewers read output, send input/resize)
	MsgTerminalOutput        MsgType = "terminal.output"
	MsgTerminalInput         MsgType = "terminal.input"
	MsgTerminalResize        MsgType = "terminal.resize"
	MsgTerminalReplayRequest MsgType = "terminal.replay_request"
	MsgTerminalReplay        MsgType = "terminal.replay"

	// Subscription (viewer <-> server)
	MsgSubscribe   MsgType = "session.subscribe"
	MsgUnsubscribe MsgType = "session.unsubscribe"

	// Heartbeat, snapshot, errors
	MsgHeartbeat    MsgType = "heartbeat"
	MsgSessionState MsgType = "session.state" // full snapshot push on subscribe
	MsgError        MsgType = "error"
)

// Role defines a device's role in a session.
type Role string

const (
	RoleOwner  Role = "owner"  // creator - full control
	RoleViewer Role = "viewer" // subscriber - read output, send input/resize
)

// Message is the unified envelope for all WebSocket traffic.
type Message struct {
	Type      string                 `json:"type"`
	SessionID string                 `json:"session_id,omitempty"`
	Timestamp int64                  `json:"timestamp"`
	Payload   map[string]interface{} `json:"payload,omitempty"`
}

// AuthPayload is the payload for auth messages.
type AuthPayload struct {
	Token string `json:"token"`
}

// AuthResponsePayload is the payload for auth_response messages.
type AuthResponsePayload struct {
	Success    bool   `json:"success"`
	DeviceID   string `json:"device_id"`
	DeviceType string `json:"device_type"`
	Message    string `json:"message,omitempty"`
}

// SessionSnapshot represents the full state of a session for sync.
type SessionSnapshot struct {
	SessionID string `json:"session_id"`
	OwnerID   string `json:"owner_id"`
	Title     string `json:"title"`
	Cols      int    `json:"cols"`
	Rows      int    `json:"rows"`
	Status    string `json:"status"`
	TaskState string `json:"task_state,omitempty"`
	Preview   string `json:"preview,omitempty"`
	Activity  string `json:"activity,omitempty"`
}

// SessionListPayload is the payload for session list responses.
type SessionListPayload struct {
	Sessions []SessionSnapshot `json:"sessions"`
}

// ErrorPayload is the payload for error messages.
type ErrorPayload struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ─── Legacy aliases for backward compat during transition ─────────────────

// AuthRequest represents an authentication request (legacy alias)
type AuthRequest struct {
	Token string `json:"token"`
}

// AuthResponse represents an authentication response (legacy alias)
type AuthResponse struct {
	Success  bool   `json:"success"`
	DeviceID string `json:"device_id,omitempty"`
	Message  string `json:"message,omitempty"`
}
